### ISSUE TITLE
Add playbook for delatore bot provisioning

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud-infra/kapellmeister#7]
Add playbook and role for installing https://github.com/opentelekomcloud-infra/delatore onto test_host

**Comment by anton-sidelnikov** [comment]
Will do it after implementing of #12

**Comment by outcatcher** [comment]
Delatore will have possibility to be used as module: opentelekomcloud-infra/delatore#23

**Comment by outcatcher** [comment]
Waiting for https://github.com/opentelekomcloud-infra/delatore/projects/1 to be closed.
